# Этап сборки
FROM node:18-alpine as builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .

# Увеличиваем лимит памяти для Node.js
ENV NODE_OPTIONS=--max-old-space-size=4096

RUN npm run build

# Основной этап
FROM nginx:1.25-alpine
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
